# 트랜잭션 전파를 활용해보자.

이전에 배운 개념인 [트랜잭션 전파]()를 활용하여 예제를 작성해보자.  

## 요구사항 및 로직 작성

### 요구사항

\- 회원 관리 (등록,수정,조회)
\- 회원정보 변경 이력 로깅

## 예제 코드

데이터베이스는 스프링 부트가 제공하는 인메모리DB를 사용해서 진행   

### Member , Log (Entity)

Member 엔티티는 식별자인 id 와 username으로 구성  
Log 엔티티는 id와 message로 구성  
엔티티 식별자 생성 규칙은 기본값을 사용.  

### MemberService

```java
@Slf4j
@Service
@RequiredArgsConstructor
public class MemberService {

    private final MemberRepository memberRepository;
    private final LogRepository logRepository;

    public void joinV1(String username) {
        Member member = new Member(username);
        Log logMessage = new Log(username);
        log.info("== memberRepository 호출 시작 ==");
        memberRepository.save(member);
        log.info("== memberRepository 호출 종료 ==");
        log.info("== logRepository 호출 시작 ==");
        logRepository.save(logMessage);
        log.info("== logRepository 호출 종료 ==");
    }
}
```

### MemberRepository, LogRepository

- MemberRepository

    MemberRepository의 로직은 간단하므로 생략

    ```java
    @Slf4j
    @Repository
    @RequiredArgsConstructor
    public class MemberRepository {

        private final EntityManager em;

        //저장
        @Transactional //outerTxoff
        public void save(Member member){}
        //이름으로 단건 조회
        public Optional<Member> find(String username) {}
        //전체 조회
        public List<Member> findAll(){}
    }
    ```

- LogRepository

    ```java
    @Slf4j
    @Repository
    @RequiredArgsConstructor
    public class LogRepository {

        private final EntityManager em;

        @Transactional //outerTxoff
        public void save(Log logMessage) {
            log.info("log 저장");
            em.persist(logMessage);
            //메세지에 '로그예외'가 있으면 예외 발생
            if (logMessage.getMessage().contains("로그예외")) {
                log.info("log 저장시 예외 발생");
                throw new RuntimeException("예외 발생");
            }
        }
        //메세지로 단건 조회
        public Optional<Log> find(String message) {}
        //전체 조회
        public List<Log> findAll(){}
    }
    ```

- MemberServiceTest (테스트 코드)

    ```java
    @Slf4j
    @SpringBootTest
    class MemberServiceTest {

        @Autowired
        MemberService memberService;
        @Autowired
        MemberRepository memberRepository;
        @Autowired
        LogRepository logRepository;

        /**
         * 테스트 종료 전 멤버와 로그 테이블 출력
         */
        @AfterEach
        void afterprintdb(){
            log.info("====member list====");
            memberRepository.findAll().stream().forEach(m -> log.info("{}",m));
            log.info("====log list====");
            logRepository.findAll().stream().forEach(l -> log.info("{}",l));
        }

        //테스트코드
    }
    ```

    afterprintdb()는 테스트 종료 후 인메모리DB에 있는 엔티티들을 출력하기 위한 메서드이다.  

## 트랜잭션 전파 활용 예제

위에서 예제에 필요한 서비스와 리포지토리 그리고 필요한 엔티티를 작성하였다.  
이제 테스트를 통해 전파가 없다는 가정하에 트랜잭션 범위에 따른 예제의 결과와 전파옵션을 활용하여 커밋과 롤백 시 어떻게 활용하고 어떤 결과가 나오는지 알아보자.  

### 전파옵션을 적용 안할 경우 예제

#### 서비스 X 리포지토리 O

리포지토리에만 트랜잭션이 선언되 있는 경우를 보자.  

- 테스트 코드
    ```java
    /**
     * MemberService noTX
     * MemberRepository @Transactional
     * LogRepository @Transactional
     * 각각의 단독 트랜잭션 2개
     */
    @Test
    void outerTxOff_success() {
        //given
        String username = "outerTxOff_success";
        //when: Member 저장 및 로그 저장
        memberService.joinV1(username);
        //then: 모든 데이터가 정상 저장된다.
        assertTrue(memberRepository.find(username).isPresent());
        assertTrue(logRepository.find(username).isPresent());
    }
    /**
     * MemberService noTX
     * MemberRepository @Transactional
     * LogRepository @Transactional( 예외 발생 )
     * 로그 리포티토리 예외 발생
     */
    @Test
    void outerTxOff_fail() {
        //given
        String username = "로그예외_outerTxOff_fail";
        //when
        assertThatThrownBy(() -> memberService.joinV1(username)).isInstanceOf(RuntimeException.class);
        //then: LogRepo만 롤백 후 MemberRepo는 정상적으로 커밋
        assertTrue(memberRepository.find(username).isPresent());
        assertTrue(logRepository.find(username).isEmpty());
    }
    ```

![image](https://github.com/9ony/9ony/assets/97019540/4b20cbb6-6e82-4caf-8c48-7ae916f98834)

success()는 쉬우니 설명을 넘어가도록 하겠다.  
fail()은 username에 로그예외가 포함되어 있으므로 logRepository에서 save()시 예외가 발생할 것이다.  
그로인해 롤백되어 Log는 저장을 하지 않고 Member만 저장되었다.  
그 이유는 그림 처럼 Member와 Log의 리포지토리는 서로 다른 트랜잭션이기 때문에 관여하지 않게된다.  

#### 서비스 O 리포지토리 X

이번에는 서비스에만 트랜잭션이 걸려있는 경우를 테스트해보자!  

✔ 서비스 계층에 JoinV1()메서드에 트랜잭션 선언을 해주고 각각의 리포지토리는 잠시 트랜잭션 어노테이션을 주석처리 해주자.  

- 테스트 코드

    ```java
    /**
     * MemberService @Transactional
     * MemberRepository noTX
     * LogRepository noTX
     * 서비스계층에만 트랜잭션 적용  
     */
    @Test
    void outerTxOn() {
        //given
        String username = "outerTxOn";
        //when
        memberService.joinV1(username);
        //then: 모든 데이터가 정상 저장된다.
        assertTrue(memberRepository.find(username).isPresent());
        assertTrue(logRepository.find(username).isPresent());
    }

    /**
     * MemberService @Transactional
     * MemberRepository noTX
     * LogRepository noTX ( 예외 발생 )
     * 로그 리포티토리 예외 발생
     */
    @Test
    void outerTxOn_fail() {
        //given
        String username = "로그예외_outerTxOn_fail";
        //when 
        assertThatThrownBy(() -> memberService.joinV1(username)).isInstanceOf(RuntimeException.class);
        //then: 모든 데이터가 저장되지 않는다. ? 로그 저장시 예외 발생  
        assertTrue(memberRepository.find(username).isEmpty());
        assertTrue(logRepository.find(username).isEmpty());
    }
    ```

![image](https://github.com/9ony/9ony/assets/97019540/004b3567-722b-4a52-a730-1f4704cd03b5)

서비스 계층에 트랜잭션을 적용 함으로써 로그에서 예외가 발생하게 되면 Member도 저장하지 않게되면서 이제 Member 저장과 Log 기록 둘다 성공해야지 데이터가 저장되므로 정합성을 지키게 된다.  
이는 각각의 리포지토리가 같은 트랜잭션을 사용하고 있기 때문이다.  

#### 문제점 (트랜잭션 전파가 없을때)  

해당 문제점은 트랜잭션 전파가 안된다고 가정했을 때 문제점이다.  

![image](https://github.com/9ony/9ony/assets/97019540/227cab01-84f9-4565-b59e-45b4241b277e)

만약 다른 서비스 계층에서 각각의 리포지토리를 호출한다고 생각해보자.  
이러면 만약 Member만 저장하거나 Log만 저장할 경우에는 트랜잭션 적용이 안된다.  
그렇다고 해서 `MemberRepository와 LogRepository에 각각 트랜잭션을 적용`하게 된다면 `Member와 Log의 데이터가 일치하지 않게 되는 경우도 발생`된다.  

이러한 문제를 해결하려면 아래 그림과 같이 트랜잭션이 적용된 메서드와 기존 트랜잭션 A에 포함시키는 메서드(트랜잭션 적용 X)가 각각 있어야 한다.  

![image](https://github.com/9ony/9ony/assets/97019540/0a13737d-ff83-40e2-86c0-3f677649f782)

만약 이러한 서비스의 메서드가 점점 많아진다면 이러한 코드는 점점 많아지게 될것이다.  
즉, 포함될 메서드와 단독으로 트랜잭션이 적용될 메서드를 각각 만듬으로써 코드가 많아지고 복잡해짐.  

해당 문제를 해결하기 위해 앞서 배운 트랜잭션 전파가 필요하다.  

### 전파옵션 적용 예제

전파 개념이 없다고 가정했을때 트랜잭션을 적용한 메서드와 적용하지 않는 메서드를 각각 만들어 주어야 했다.  
해당 문제를 트랜잭션 전파를 활용하여 서비스에 적용해보자.  
`서비스와 리포지토리 메서드에 전부 @Transactional을 선언`해주자.  

#### REQUIRED 옵션

해당 옵션은 트랜잭션이 존재한다면 참여하고 없으면 새롭게 시작하는 옵션이다.  

- 테스트 코드
    ```java
    /**
     * MemberService @Transactional
     * MemberRepository @Transactional
     * LogRepository @Transactional
     */
    @Test
    void propagationTxOn_success() {
        //given
        String username = "propagationTxOn_success";
        //when
        memberService.joinV1(username);
        //then: 모든 데이터가 정상 저장된다.
        assertTrue(memberRepository.find(username).isPresent());
        assertTrue(logRepository.find(username).isPresent());
    }

    /**
     * MemberService @Transactional
     * MemberRepository @Transactional
     * LogRepository @Transactional (예외 발생)
     */
    @Test
    void propagationTxOn_fail() {
        //given
        String username = "로그예외_propagationTxOn_fail";
        //when
        assertThatThrownBy(() -> memberService.joinV1(username)).isInstanceOf(RuntimeException.class);
        //then: 모든 데이터가 롤백
        assertTrue(memberRepository.find(username).isEmpty());
        assertTrue(logRepository.find(username).isEmpty());
    }
    ```

    테스트를 실행해보면 서비스에만 트랜잭션을 적용했을때 처럼 동작한다.  
    트랜잭션이 시작했던 서비스에서 각각의 리포지토리의 메서드를 호출했는데, 분명 @Transactional이 적용되어 있지만 트랜잭션을 새로 시작하지 않았다.  
    상위 메서드에서 시작한 트랜잭션에 참여한 것이다.  
    트랜잭션을 참여한 메서드들은 커밋을 하더라도 실제 트랜잭션을 커밋하지 않는다.  
    또 `롤백을 할 경우에는 참여하고 있는 트랜잭션에 rollbackOnly를 설정`하는데, 해당 설정이 된 경우에는 `롤백을 수행`하게 된다.  


#### REQUIRED 예외 복구

자 만약 로그등록에 실패하더라도 회원가입은 그대로 진행하려면 어떻게 해야될까?  
트랜잭션에 참여한 메서드는 예외가 발생해 롤백하게 된다면 `rollbackOnly를 설정`한다고 했다.  
그래서 상위 메서드까지 전달된 `예외를 잡아서 복구하더라도 롤백하게 된다`.  
예제로 확인해보자!!  

- MemberService JoinV2 추가
    ```java
    @Transactional
    public void joinV2(String username) {
        Member member = new Member(username);
        Log logMessage = new Log(username);
        log.info("== memberRepository 호출 시작 ==");
        memberRepository.save(member);
        log.info("== memberRepository 호출 종료 ==");
        log.info("== logRepository 호출 시작 ==");
        try {
            logRepository.save(logMessage);
        } catch (RuntimeException e) {
            //오류 복구 (중요)
            log.info("log 저장에 실패했습니다. logMessage={}", logMessage.getMessage());
            log.info("정상 흐름 변환");
        }
        log.info("== logRepository 호출 종료 ==");
    }
    ```

    보면 서비스에서 로그를 저장할때 발생하는 예외를 복구하고 있다.  
    joinV2로 호출하게 되면 롤백이 되는지 확인해보자.  

- 테스트 코드
    ```java
    /**
     * MemberService @Transactional (예외 복구 JoinV2)
     * MemberRepository @Transactional
     * LogRepository @Transactional ( 예외 발생 )
     * logRepository에서 발생한 예외를 MemberService에서 복구함
     */
    @Test
    void recoverException_fail() {
        //given
        String username = "로그예외_recoverException_fail";
        //when
        assertThatThrownBy(() -> memberService.joinV2(username)).isInstanceOf(UnexpectedRollbackException.class);
        //then: 모든 데이터가 롤백  
        assertTrue(memberRepository.find(username).isEmpty());
        assertTrue(logRepository.find(username).isEmpty());
    }
    ```

- 동작 그림

    ![image](https://github.com/9ony/9ony/assets/97019540/a64130e5-01ff-46f8-a2ed-bb2870c5dc72)

    결과를 보면 내부 트랜잭션에서 rollbackOnly를 설정하기 때문에 예외를 복구하면서 정상 흐름을 가지더라도 외부 트랜잭션에서 커밋을 호출해도 rollbackOnly가 설정되어 있기 때문에 트랜잭션이 롤백되면서 UnexpectedRollbackException이 발생하게 된다.  


#### REQUIRES_NEW 예외 복구  

REQUIRES_NEW 옵션을 사용하게 되면 @Transactional이 시작될때 외부 트랜잭션이 있더라도 다른 커넥션을 가지고와서 새로운 트랜잭션을 시작한다.  
해당 옵션을 통해 로그를 남기는 중에 실패하더라도 회원 가입은 유지할 수 있다.  

- LogRepository 수정
    ```java
    //@Transactional //outerTxoff
    @Transactional(propagation = Propagation.REQUIRES_NEW)
    public void save(Log logMessage) {
    ```

- 테스트 코드

    ```java
    /**
     * MemberService @Transactional (예외 복구 JoinV2)
     * MemberRepository @Transactional
     * LogRepository @Transactional(REQUIRES_NEW) ( 예외 발생 )
     * logRepository에서 발생한 예외를 MemberService에서 복구함
     */
    @Test
    void recoverException_success() {
        //given
        String username = "로그예외_recoverException_success";
        //when
        memberService.joinV2(username);
        //then: log만 롤백
        assertTrue(memberRepository.find(username).isPresent());
        assertTrue(logRepository.find(username).isEmpty());
    }
    ```

- 동작 그림

    ![image](https://github.com/9ony/9ony/assets/97019540/99c41cf5-d9b9-45ab-9099-124065229c5b)

    테스트가 정상적으로 통과되는 것을 볼 수 있다.  
    Log는 롤백되어서 데이터가 저장안되었지만 Member의 회원 가입은 정상적으로 되었다.  
    이는 전파옵션이 REQUIRES_NEW로 설정되었기 때문에 기존 커넥션이 아닌 새로운 커넥션으로 트랜잭션을 시작하기 때문에 외부 트랜잭션에 영향을 주지 않고 해당 트랜잭션은 롤백하고 발생한 예외를 호출한 클라이언트에서 처리해줌으로써 서비스는 그대로 정상흐름을 가져가서 커밋되는 것이다.   

#### 또다른 방법

- 테스트 코드
    ```java
    @Test
    void memberFacade(){
        String username = "로그예외_memberFacade";
        MemberFacade memberFacade = new MemberFacade(memberService,logRepository);
        memberFacade.save(username);
    }

    //트랜잭션 자체를 분리
    static class MemberFacade{
        private final MemberService memberService;
        private final LogRepository logRepository;
        MemberFacade(MemberService memberService,LogRepository logRepository){
            this.memberService = memberService;
            this.logRepository = logRepository;
        }
        public void save(String username){
            memberService.joinV3(username); // 트랜잭션A
            Log logMessage = new Log(username);
            try {
                logRepository.save(logMessage); // 트랜잭션B
            }catch (RuntimeException e){
                log.info("로그 저장 중 예외 발생",e);
            }
        }
    }
    ```

위 코드처럼 애초에 멤버를 저장하는 서비스와 로그를 저장하는 트랜잭션을 분리하기 위해 앞단에서 이를 분리해서 실행시키는 클래스를 하나 만들어서 해결해도 된다.  
계층을 추가한다고 보면된다.  